/* Code generated by cmd/cgo; DO NOT EDIT. */

/* package mod */


#line 1 "cgo-builtin-export-prolog"

#include <stddef.h> /* for ptrdiff_t below */

#ifndef GO_CGO_EXPORT_PROLOGUE_H
#define GO_CGO_EXPORT_PROLOGUE_H

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef struct { const char *p; ptrdiff_t n; } _GoString_;
#endif

#endif

/* Start of preamble from import "C" comments.  */




/* End of preamble from import "C" comments.  */


/* Start of boilerplate cgo prologue.  */
#line 1 "cgo-gcc-export-header-prolog"

#ifndef GO_CGO_PROLOGUE_H
#define GO_CGO_PROLOGUE_H

typedef signed char GoInt8;
typedef unsigned char GoUint8;
typedef short GoInt16;
typedef unsigned short GoUint16;
typedef int GoInt32;
typedef unsigned int GoUint32;
typedef long long GoInt64;
typedef unsigned long long GoUint64;
typedef GoInt64 GoInt;
typedef GoUint64 GoUint;
typedef __SIZE_TYPE__ GoUintptr;
typedef float GoFloat32;
typedef double GoFloat64;
typedef float _Complex GoComplex64;
typedef double _Complex GoComplex128;

/*
  static assertion to make sure the file is being used on architecture
  at least with matching size of GoInt.
*/
typedef char _check_for_64_bit_pointer_matching_GoInt[sizeof(void*)==64/8 ? 1:-1];

#ifndef GO_CGO_GOSTRING_TYPEDEF
typedef _GoString_ GoString;
#endif
typedef void *GoMap;
typedef void *GoChan;
typedef struct { void *t; void *v; } GoInterface;
typedef struct { void *data; GoInt len; GoInt cap; } GoSlice;

#endif

/* End of boilerplate cgo prologue.  */

#ifdef __cplusplus
extern "C" {
#endif


extern char* SignTransaction(char* p0);

extern char* DecodeTransaction(char* p0);

extern char* SignCreateCoinTransaction(char* p0);

extern char* SignSellCoinTransaction(char* p0);

extern char* SignBuyCoinTransaction(char* p0);

extern char* SignSellAllCoinTransaction(char* p0);

extern char* SignDeclareCandidacyTransaction(char* p0);

extern char* SignDelegateTransaction(char* p0);

extern char* SignUnbondTransaction(char* p0);

extern char* SignSetCandidateOffTransaction(char* p0);

extern char* SignSetCandidateOnTransaction(char* p0);

extern char* SignRedeemCheckTransaction(char* p0);

extern char* SignEditCandidateTransaction(char* p0);

extern char* SignMultiSendTransaction(char* p0);

#ifdef __cplusplus
}
#endif
